### ISSUE TITLE
O4 gRPC Module For Communication Layer

### ISSUE THREAD

**Issue by hardlyhuman** [aidecentralized/sonar#20] opened 2024-07-18 15:53 UTC
As an initial step towards this Objective, I propose migrating the current MPI version of CommUtils to gRPC. It can be done in following steps:
1. Define the gRPC service and messages in a .proto file.
2. Generate the gRPC code from the .proto file.
3. Implement the gRPC server with the necessary services.
4. Implement the gRPC client to replace the MPI communication calls.

if nothing else is priority now, I can get started with this

**Comment by tremblerz** [comment] 2024-07-18 18:44
Thanks for bringing it up! Xavier and Gautam are working towards this.

**Comment by hardlyhuman** [comment] 2024-08-05 17:53
Hi @gautamjajoo , I want to check if I can help you with anything in the development of the gRPC Module

**Comment by tremblerz** [comment] 2024-09-01 00:40
The issue is fixed now with a new communication manager API

**Closed by tremblerz** 2024-09-01 00:40 UTC
Labels: enhancement
